import Head from 'next/head'
import { FC, ReactElement } from 'react';
import Navbar from '../Navbar'
import styles from './Main.module.css'

interface Props {
  children: ReactElement | ReactElement[];
  title: string;
}

export const MainLayout:FC<Props> = ({children, title}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app - kev" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />

          <main className={styles.main}>
            <h1>{title}</h1>
            { children }
          </main>
        </div>
      )
}
